# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='是否被占用'),
        ),
    ]
