# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_del',
        ),
    ]
