# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_remove_device_is_del'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='env_type',
            field=models.CharField(default='andorid_pos', help_text='如:android_mobile,andorid_pos,computer...', max_length=200, verbose_name='产品型号'),
            preserve_default=False,
        ),
    ]
