# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_device_env_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='env_type',
            field=models.CharField(help_text='如:android_mobile,android_pos,computer...', max_length=200, verbose_name='产品型号'),
        ),
    ]
