# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20180703_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.CharField(default='', help_text='设备版本', max_length=30, verbose_name='设备版本'),
        ),
    ]
