# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecuteinfo',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='taskexecuteinfo',
            name='exec_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='执行时长'),
        ),
        migrations.AlterField(
            model_name='taskexecuteinfo',
            name='failure',
            field=models.TextField(blank=True, null=True, verbose_name='失败原因'),
        ),
    ]
