# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 20:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='用例标题')),
                ('case_type', models.CharField(choices=[('functional', '功能测试'), ('performance', '性能测试'), ('api', '接口测试'), ('safe', '安全测试'), ('other', '其他')], default='functional', max_length=20, verbose_name='用例类型')),
                ('test_type', models.CharField(blank=True, help_text='如：冒烟测试，场景测试等类型', max_length=20, verbose_name='测试类型')),
                ('test_precondition', models.TextField(blank=True, null=True, verbose_name='前置条件')),
                ('test_step', models.TextField(blank=True, null=True, verbose_name='测试步骤')),
                ('enclosure_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='附件标题')),
                ('enclosure', models.FileField(blank=True, null=True, upload_to='case/enclosure', verbose_name='用例附件')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime(2018, 6, 14, 20, 37, 53, 886560), verbose_name='修改时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='CaseScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50, verbose_name='脚本用例名称')),
                ('script_file', models.FileField(blank=True, null=True, upload_to='case/script', verbose_name='脚本文件')),
                ('upload_file', models.BooleanField(default=False, verbose_name='是否上传文件')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateField(default=datetime.datetime(2018, 6, 14, 20, 37, 53, 887601), verbose_name='修改时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_script', to='case.Case', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '用例脚本',
                'verbose_name_plural': '用例脚本',
            },
        ),
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父类目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_module_cat', to='case.ModuleCategory', verbose_name='父类目')),
            ],
            options={
                'verbose_name': '模块类别',
                'verbose_name_plural': '模块类别',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('product_type', models.CharField(choices=[('mobile', '手机端应用'), ('web', '网页'), ('network', '网络设备'), ('other', '其他')], default='mobile', max_length=20, verbose_name='产品类型')),
                ('package_name', models.CharField(blank=True, help_text='如:apk包名', max_length=200, null=True, verbose_name='包名')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ScriptExcConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_path', models.CharField(max_length=200, verbose_name='用例前缀路径')),
            ],
            options={
                'verbose_name': '脚本配置',
                'verbose_name_plural': '脚本配置',
            },
        ),
        migrations.AddField(
            model_name='modulecategory',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Product', verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='casescript',
            name='script_exc_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.ScriptExcConfig', verbose_name='脚本执行配置'),
        ),
        migrations.AddField(
            model_name='case',
            name='product_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.ModuleCategory', verbose_name='产品模块类别'),
        ),
    ]
