# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20180716_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 17, 9, 24, 986885), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 17, 9, 24, 989104), verbose_name='修改时间'),
        ),
    ]
