# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20180615_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 19, 47, 22, 115588), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 19, 47, 22, 116635), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='modulecategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
