# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20180716_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 19, 8, 42, 899118), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 19, 8, 42, 900816), verbose_name='修改时间'),
        ),
    ]
