# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20180716_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 19, 42, 31, 672143), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 19, 42, 31, 674298), verbose_name='修改时间'),
        ),
    ]
