# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20180619_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecategory',
            old_name='product_category',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 20, 15, 57, 476501), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 20, 15, 57, 477583), verbose_name='修改时间'),
        ),
    ]
