# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20180719_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casescript',
            name='execute_env',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 18, 22, 10, 155639), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 18, 22, 10, 157006), verbose_name='修改时间'),
        ),
    ]
