# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20180619_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='用例集名', max_length=30, verbose_name='用例集名')),
                ('desc', models.TextField(default='', help_text='用例集描述', verbose_name='用例集描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseset', to='case.ModuleCategory', verbose_name='产品模块类别')),
            ],
            options={
                'verbose_name': '用例集',
                'verbose_name_plural': '用例集',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 20, 23, 45, 265425), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 20, 23, 45, 266970), verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.CaseSet', verbose_name='用例集'),
        ),
    ]
