# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20180620_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='product_module',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='caseset',
            old_name='product_module',
            new_name='module',
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 20, 42, 41, 971751), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 20, 42, 41, 972849), verbose_name='修改时间'),
        ),
    ]
