# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20180721_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 16, 55, 45, 975224), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 16, 55, 45, 976587), verbose_name='修改时间'),
        ),
    ]
