# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20180724_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 16, 5, 48, 946811), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 16, 5, 48, 948219), verbose_name='修改时间'),
        ),
    ]
