# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 17:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0008_auto_20180620_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReleteCaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用例与测试集关联',
                'verbose_name_plural': '用例与测试集关联',
            },
        ),
        migrations.CreateModel(
            name='CaseReleteTestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用例与测试任务关联',
                'verbose_name_plural': '用例与测试任务关联',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_state', models.CharField(choices=[('not_start', '未开始'), ('executing', '执行中'), ('block', '执行中断'), ('finish', '执行完成')], default='not_start', max_length=20, verbose_name='任务状态')),
                ('total_case_num', models.IntegerField(blank=True, null=True, verbose_name='总用例数')),
                ('success_case_num', models.IntegerField(blank=True, null=True, verbose_name='成功用例数')),
                ('fail_case_num', models.IntegerField(blank=True, null=True, verbose_name='失败用例数')),
                ('block_case_num', models.IntegerField(blank=True, null=True, verbose_name='阻塞用例数')),
                ('desc', models.TextField(default='', help_text='描述', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('execut_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('execut_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TestTask.execut_user+', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
            },
        ),
        migrations.RemoveField(
            model_name='scriptexcconfig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_set',
        ),
        migrations.RemoveField(
            model_name='casescript',
            name='script_exc_config',
        ),
        migrations.AddField(
            model_name='casescript',
            name='prefix_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用例前缀路径'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 41, 35, 578513), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 41, 35, 579916), verbose_name='修改时间'),
        ),
        migrations.DeleteModel(
            name='ScriptExcConfig',
        ),
        migrations.AddField(
            model_name='casereletetesttask',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Case', verbose_name='用例'),
        ),
        migrations.AddField(
            model_name='casereletetesttask',
            name='case_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.CaseSet', verbose_name='用例集'),
        ),
        migrations.AddField(
            model_name='casereletetesttask',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.TestTask', verbose_name='测试任务'),
        ),
        migrations.AddField(
            model_name='casereletecaseset',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='casereletecaseset',
            name='case_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.CaseSet', verbose_name='用例集'),
        ),
    ]
