# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20180727_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 11, 15, 35, 858259), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 11, 15, 35, 859758), verbose_name='修改时间'),
        ),
    ]
