# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 17:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20180621_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 45, 45, 626855), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 45, 45, 628170), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='execut_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_testTask', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
    ]
