# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20180730_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 18, 16, 23, 789895), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 18, 16, 23, 791431), verbose_name='修改时间'),
        ),
    ]
