# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20180621_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtask',
            name='execut_time',
        ),
        migrations.AddField(
            model_name='testtask',
            name='execut_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行结束时间'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='execut_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行开始时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 56, 46, 518693), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 17, 56, 46, 520008), verbose_name='修改时间'),
        ),
    ]
