# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20180730_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 14, 9, 21, 395248), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 14, 9, 21, 396676), verbose_name='修改时间'),
        ),
    ]
