# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 10:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20180621_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='re_execut_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='失败重跑次数'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 10, 4, 43, 205578), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 10, 4, 43, 208313), verbose_name='修改时间'),
        ),
    ]
