# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20180622_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.ModuleCategory', verbose_name='产品模块'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 15, 56, 48, 993602), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 25, 15, 56, 48, 994784), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='caseset',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseset', to='case.ModuleCategory', verbose_name='产品模块'),
        ),
    ]
