# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20180809_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 17, 52, 43, 157421), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 14, 17, 52, 43, 159417), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='task_state',
            field=models.CharField(choices=[('not_start', '未开始'), ('executing', '执行中'), ('block', '执行中断'), ('finish', '执行完成'), ('stop', '执行停止')], default='not_start', max_length=20, verbose_name='任务状态'),
        ),
    ]
