# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_auto_20180814_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 15, 25, 41, 93753), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 15, 25, 41, 95178), verbose_name='修改时间'),
        ),
    ]
