# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_auto_20180625_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereletecaseset',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='casereletetesttask',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 34, 10, 311659), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 16, 34, 10, 312750), verbose_name='修改时间'),
        ),
    ]
