# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_auto_20180821_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='product',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.Product', verbose_name='产品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 17, 52, 52, 295004), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 17, 52, 52, 296387), verbose_name='修改时间'),
        ),
    ]
