# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-19 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_auto_20181119_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 0, 59, 465839), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 18, 0, 59, 467195), verbose_name='修改时间'),
        ),
    ]
