# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-29 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_auto_20180629_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 15, 59, 24, 98493), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 15, 59, 24, 99661), verbose_name='修改时间'),
        ),
    ]
