# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_auto_20180703_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 19, 7, 5, 259852), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 19, 7, 5, 262032), verbose_name='修改时间'),
        ),
    ]
