# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_auto_20180703_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='casescript',
            name='execute_env',
            field=models.CharField(default='andorid_pos', help_text='产品型号如:android_mobile,andorid_pos,computer...', max_length=200, verbose_name='执行环境'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 20, 15, 16, 703315), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 3, 20, 15, 16, 704834), verbose_name='修改时间'),
        ),
    ]
