# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0022_auto_20180703_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 14, 48, 9, 101826), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='name',
            field=models.CharField(max_length=50, verbose_name='脚本名称'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='prefix_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='脚本执行前缀路径'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 14, 48, 9, 103106), verbose_name='修改时间'),
        ),
    ]
