# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_auto_20180706_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 16, 25, 8, 590653), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 16, 25, 8, 591953), verbose_name='修改时间'),
        ),
    ]
