# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_auto_20180709_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 16, 54, 32, 34252), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casescript',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 16, 54, 32, 35709), verbose_name='修改时间'),
        ),
    ]
