# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20180721_1822'),
        ('uitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApKConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=30, verbose_name='名称')),
                ('app', models.FileField(upload_to='app/', verbose_name='被测应用')),
                ('package_name', models.CharField(blank=True, help_text='apk包名', max_length=200, null=True, verbose_name='包名')),
                ('package_start_activity', models.CharField(blank=True, help_text='apk启动页', max_length=200, null=True, verbose_name='apk启动页')),
                ('test_app', models.FileField(blank=True, null=True, upload_to='app/', verbose_name='测试应用')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '执行环境配置',
                'verbose_name_plural': '执行环境配置',
            },
        ),
        migrations.CreateModel(
            name='DeviceRelateApK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('apKConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_device', to='uitest.ApKConfig', verbose_name='apk')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备关联',
                'verbose_name_plural': '设备关联',
            },
        ),
        migrations.CreateModel(
            name='RemoteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=30, null=True, verbose_name='关键字')),
                ('type', models.CharField(choices=[('appium', 'Appimu'), ('selenium', 'Selenium')], max_length=30, verbose_name='类型')),
                ('host', models.CharField(max_length=30, verbose_name='ip')),
                ('port', models.CharField(max_length=10, verbose_name='端口号')),
                ('device_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='设备mode名称')),
                ('device_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='设备device_id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'url数据配置',
                'verbose_name_plural': 'url数据配置',
            },
        ),
        migrations.RemoveField(
            model_name='devicerelateenv',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicerelateenv',
            name='env',
        ),
        migrations.RemoveField(
            model_name='envconfig',
            name='app',
        ),
        migrations.RemoveField(
            model_name='envconfig',
            name='test_app',
        ),
        migrations.DeleteModel(
            name='DeviceRelateEnv',
        ),
        migrations.AddField(
            model_name='remoteservice',
            name='env_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_service', to='uitest.EnvConfig', verbose_name='测试数据配置'),
        ),
        migrations.AddField(
            model_name='apkconfig',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_apks', to='uitest.EnvConfig', verbose_name='环境'),
        ),
    ]
