# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0002_auto_20180721_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerelateapk',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='是否就绪'),
        ),
    ]
