# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uitest', '0003_devicerelateapk_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apkconfig',
            options={'verbose_name': 'APK配置', 'verbose_name_plural': 'APK配置'},
        ),
        migrations.AlterField(
            model_name='apkconfig',
            name='name',
            field=models.CharField(default='', help_text='名称', max_length=300, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='envconfig',
            name='data_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataconfig.TestDataConfig', verbose_name='环境数据配置'),
        ),
    ]
