# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_sync_time'),
        ('uitest', '0004_auto_20180730_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=300, verbose_name='名称')),
                ('ready', models.BooleanField(default=False, verbose_name='是否就绪')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'web配置',
                'verbose_name_plural': 'web配置',
            },
        ),
        migrations.AlterField(
            model_name='envconfig',
            name='app_script_type',
            field=models.CharField(choices=[('python', 'python'), ('robotium', 'robotium')], max_length=30, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='webconfig',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_webs', to='uitest.EnvConfig', verbose_name='环境'),
        ),
    ]
