# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('database_host', models.CharField(max_length=100, verbose_name='数据库链接')),
                ('database_port', models.CharField(max_length=10, verbose_name='数据库端口')),
                ('database_user', models.CharField(max_length=100, verbose_name='数据库用户名')),
                ('database_password', models.CharField(max_length=100, verbose_name='数据库密码')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据库配置',
                'verbose_name_plural': '数据库配置',
            },
        ),
        migrations.CreateModel(
            name='TestDataConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type', models.CharField(choices=[('test', '测试环境'), ('gld', '灰度环境'), ('pro', '生产环境')], max_length=30, verbose_name='类型')),
                ('web_url', models.CharField(max_length=100, verbose_name='web域名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试数据配置',
                'verbose_name_plural': '测试数据配置',
            },
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='test_data_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_bases', to='dataconfig.TestDataConfig', verbose_name='测试数据配置'),
        ),
    ]
