# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfig', '0002_auto_20180716_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='keyword',
            field=models.CharField(default='default', max_length=30, verbose_name='关键字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urldataconfig',
            name='keyword',
            field=models.CharField(default='default', max_length=30, verbose_name='关键字'),
            preserve_default=False,
        ),
    ]
