# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataconfig', '0003_auto_20180716_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdataconfig',
            options={'verbose_name': '环境配置', 'verbose_name_plural': '环境配置'},
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='test_data_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_bases', to='dataconfig.TestDataConfig', verbose_name='环境配置'),
        ),
        migrations.AlterField(
            model_name='urldataconfig',
            name='test_data_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dataconfig.TestDataConfig', verbose_name='环境配置'),
        ),
    ]
